/// <reference types="vite/client" />
declare var LazyLoad: any;
declare var GLightbox: any;
declare var gsap: any;
declare var Swiper: any;
declare var echarts: any;
declare var Inputmask: any;
declare var Handlebars: any;
declare var Choices: any;
declare var rangeSlider: any;
